[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Password protection during development
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Basic-Auth = ["PROTECTED_AREA"]}

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"